name: YaizuSample Windows CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v1
    - name: exec build
      env:
        GITHUBACTIONS: true
      run: |
        choco install openssl
        git clone -q --branch=master https://github.com/s-takeuchi/YaizuComLib.git ../YaizuComLib
        git checkout master
        cd build
        ./build_win64_svr.bat
        ./build_win64_agt.bat
    - name: exec test
      env:
        GITHUBACTIONS: true
      run: |
        cd build
        ./test.bat
